Correct changes
tms-dos17-onl/Alex-Krylov pull request #17
Opened 2023-08-24 15:08 UTC by Alex777888777

HW_10/check-parity-online.sh
HW_10/check-parity-shell.sh
HW_10/not-empty-file.sh
HW_10/geneate-testing-matrix.sh
HW_10/print-value.sh

2023-08-28 08:17 UTC, AlexPykavy requested changes

2023-08-28 08:17 UTC, AlexPykavy commented on HW_10/check-parity-online.sh
А зачем ты в конце скрипта делаешь `exit 1`? Это же выполняется всегда, даже, если переданный аргумет является числом.

И, строго говоря, достаточно одного тернарного оператора в случае проверки на чётность:
```
[[ <УСЛОВИЕ_ЧЁТНОСТИ> ]] && echo even || echo odd
```

2023-08-28 08:17 UTC, AlexPykavy commented on HW_10/check-parity-shell.sh
А зачем ты в конце скрипта делаешь `exit 1`? Это же выполняется всегда, даже, если переданный аргумет является числом.

2023-08-29 10:58 UTC, Alex777888777 commented on HW_10/check-parity-online.sh
Я все изменил

2023-08-29 10:59 UTC, Alex777888777 commented on HW_10/check-parity-online.sh
@AlexPykavy !

2023-08-31 06:18 UTC, AlexPykavy commented
Теперь у тебя конфликт в файлике `HW_12/Main.md`. Нужно поправить.

2023-09-11 11:41 UTC, merged